set MATLAB=C:\Program Files (x86)\MATLAB\R2011b
"C:\Program Files (x86)\MATLAB\R2011b\bin\win32\gmake" -f template_Final_Project_MPC5643L.mk  GENERATE_REPORT=1 INCLUDE_MDL_TERMINATE_FCN=1 COMBINE_OUTPUT_UPDATE_FCNS=1 MULTI_INSTANCE_CODE=0 INTEGER_CODE=0 PORTABLE_WORDSIZES=0 GENERATE_ERT_S_FUNCTION=0
