/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Tue Apr 12 14:59:49 2016
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void PL_Outputs_wrapper(const real32_T *H,
                          const real32_T *si,
                          const real32_T *s,
                          real32_T *lead_s,
                          real32_T *lead_u)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
         y0[0] = u0[0];
For complex signals use: y0[0].re = u0[0].re;
                         y0[0].im = u0[0].im;
                         y1[0].re = u1[0].re;
                         y1[0].im = u1[0].im;*/

int temp = 2^32-1; //max number an int can hold
int dist1 = si[0]-s[0];
int dist2 = si[4]-s[0]; 
int dist3 = si[8]-s[0];
int dist4 = si[12]-s[0];
int dist5 = si[16]-s[0];
int dist6 = si[20] - s[0];

//check if the distance between us and next car is a) less than max, and b) greater than 0
if(temp > dist1)
    if(dist1>0)
        temp = dist1;
if(temp > dist2)
    if(dist2>0)
        temp = dist2;
if(temp > dist3)
    if(dist3>0)
        temp = dist3;
if(temp > dist4)
    if(dist4>0)
        temp = dist4;
if(temp > dist5)
    if(dist5>0)
        temp = dist5;
if(temp > dist6)
    if(dist6>0)
        temp = dist6;
//now choose lead distance and speed
if(temp == 2^32-1){
    lead_s[0] = s[0]+H[0]+1; //to make sure we go into speed control mode in chart
    lead_u[0] = 0;
}
if(temp == dist1){
    lead_s[0] = si[0]; //to make sure we go into speed control mode in chart
    lead_u[0] = si[3];
}
if(temp == dist2){
    lead_s[0] = si[4]; //to make sure we go into speed control mode in chart
    lead_u[0] = si[7];
}
if(temp == dist3){
    lead_s[0] = si[8]; //to make sure we go into speed control mode in chart
    lead_u[0] = si[11];
}
if(temp == dist4){
    lead_s[0] = si[12]; //to make sure we go into speed control mode in chart
    lead_u[0] = si[15];
}
if(temp == dist5){
    lead_s[0] = si[16]; //to make sure we go into speed control mode in chart
    lead_u[0] = si[19];
}
if(temp == dist6){
    lead_s[0] = si[20]; //to make sure we go into speed control mode in chart
    lead_u[0] = si[23];
}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
